Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 50

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 60

Metrics/ClassLength:
  Max: 150

Metrics/PerceivedComplexity:
  Max: 15

Metrics/BlockNesting:
  Max: 5
